version: '3.9'
services:
  django:
    container_name: kmc_savills_app
    build:
      context: .
      dockerfile: Dockerfile.local
    command: >
      sh -c "/wait &&
             python manage.py collectstatic --no-input &&
             python manage.py makemigrations --no-input &&
             python manage.py migrate --no-input &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
    - .:/app
    ports:
    - "8000:8000"
    env_file:
      - .env
  celery:
    container_name: kmc_savills_celery
    build:
      context: .
      dockerfile: Dockerfile.local
    command: >
      sh -c "/wait &&
             celery -A mytreehouse beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - django
    environment:
      WAIT_HOSTS: django:8000
  worker:
    container_name: kmc_savills_worker
    build:
      context: .
      dockerfile: Dockerfile.local
    command: >
      sh -c "/wait && celery -A mytreehouse worker -l INFO -E --concurrency=5"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - django
    environment:
      WAIT_HOSTS: django:8000