version: '3.9'
services:
  redis:
    container_name: mytreehouse_redis_production
    image: redis:alpine
    command: "redis-server --appendonly yes --save 60 1 --loglevel warning"
    sysctls:
      - net.core.somaxconn=1024
    ports:
      - "6381:6379"
    volumes:
      - ~/mytreehouse_redis_data:/data
  django:
    container_name: mytreehouse_api_production
    build:
      context: .
      dockerfile: Dockerfile.local
    command: >
      sh -c "/wait &&
             python manage.py makemigrations --no-input &&
             python manage.py migrate --no-input &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
    - .:/app
    ports:
    - "8001:8000"
    env_file:
      - .env
  celery:
    container_name: mytreehouse_celery_production
    build:
      context: .
      dockerfile: Dockerfile.local
    command: >
      sh -c "/wait &&
             celery -A mytreehouse beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - django
    environment:
      WAIT_HOSTS: django:8000,redis:6379
  worker:
    container_name: mytreehouse_worker_production
    build:
      context: .
      dockerfile: Dockerfile.local
    command: >
      sh -c "/wait && celery -A mytreehouse worker -l INFO -E --concurrency=4"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - django
    environment:
      WAIT_HOSTS: django:8000,redis:6379