# Generated by Django 5.0.1 on 2024-01-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapyJobModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('domain', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=100)),
            ],
            options={
                'verbose_name': 'Scrapy job',
                'verbose_name_plural': 'Scrapy jobs',
                'db_table': 'scrapy_jobs',
                'ordering': ['id'],
            },
        ),
    ]
