# Generated by Django 5.0.2 on 2024-02-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapyJobModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('domain', models.URLField(null=True)),
                ('status', models.CharField(default='running', max_length=100)),
                ('attempts', models.IntegerField(default=0)),
                ('status_url', models.URLField(null=True)),
                ('supposed_to_run_at', models.DateTimeField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('finished_processed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_reason', models.TextField(null=True)),
                ('html_code', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Scrapy job',
                'verbose_name_plural': 'Scrapy jobs',
                'db_table': 'scrapy_jobs',
                'ordering': ['-supposed_to_run_at'],
            },
        ),
    ]
