# Generated by Django 5.0.1 on 2024-02-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapyjobmodel',
            options={'ordering': ['id', 'job_id', 'domain', 'status', 'attempts', 'status_url', 'supposed_to_run_at'], 'verbose_name': 'Scrapy job', 'verbose_name_plural': 'Scrapy jobs'},
        ),
        migrations.AddField(
            model_name='scrapyjobmodel',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrapyjobmodel',
            name='status_url',
            field=models.URLField(default='https://test-scrape.com'),
        ),
        migrations.AddField(
            model_name='scrapyjobmodel',
            name='supposed_to_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scrapyjobmodel',
            name='status',
            field=models.CharField(default='running', max_length=100),
        ),
    ]
