# Generated by Django 5.0.2 on 2024-02-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapyWebModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('web_url', models.URLField(unique=True)),
                ('page_number', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Scrapy web',
                'verbose_name_plural': 'Scrapy webs',
                'db_table': 'scrapy_webs',
                'ordering': ['-id'],
            },
        ),
    ]
