# Generated by Django 5.0.1 on 2024-02-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_api', '0002_scrapywebmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapywebmodel',
            name='listing_type',
            field=models.CharField(choices=[('for-sale', 'For Sale'), ('for-rent', 'For Rent')], default='for-sale', max_length=10, verbose_name='Listing Type'),
        ),
    ]
