# Generated by Django 5.0.1 on 2024-02-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_api', '0002_alter_scrapyjobmodel_options_scrapyjobmodel_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapyjobmodel',
            name='domain',
            field=models.URLField(),
        ),
    ]
