# Generated by Django 5.0.1 on 2024-02-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_api', '0003_scrapywebmodel_listing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapyjobmodel',
            name='single_page',
            field=models.BooleanField(default=False),
        ),
    ]
