# Generated by Django 5.0.1 on 2024-02-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_api', '0003_alter_scrapyjobmodel_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapyjobmodel',
            name='domain',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='scrapyjobmodel',
            name='status_url',
            field=models.URLField(null=True),
        ),
    ]
