# Generated by Django 5.0.1 on 2024-03-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_api', '0004_scrapyjobmodel_single_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapyjobmodel',
            name='is_processed',
        ),
        migrations.AddField(
            model_name='scrapyjobmodel',
            name='is_multi_page_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scrapyjobmodel',
            name='is_single_page_processed',
            field=models.BooleanField(default=False),
        ),
    ]
