# Generated by Django 5.0.1 on 2024-02-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_api', '0004_alter_scrapyjobmodel_domain_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapyjobmodel',
            options={'ordering': ['id', 'job_id', 'domain', 'status', 'attempts', 'status_url', 'supposed_to_run_at', 'html_code'], 'verbose_name': 'Scrapy job', 'verbose_name_plural': 'Scrapy jobs'},
        ),
        migrations.AddField(
            model_name='scrapyjobmodel',
            name='html_code',
            field=models.TextField(null=True),
        ),
    ]
