# Generated by Django 5.0.1 on 2024-03-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_api', '0005_remove_scrapyjobmodel_is_processed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapyjobmodel',
            name='domain',
            field=models.URLField(db_index=True, null=True),
        ),
    ]
