# Generated by Django 5.0.1 on 2024-02-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_api', '0005_alter_scrapyjobmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapyjobmodel',
            options={'ordering': ['id', 'job_id', 'domain', 'status', 'attempts', 'status_url', 'supposed_to_run_at', 'is_processed', 'finished_processed_at', 'html_code'], 'verbose_name': 'Scrapy job', 'verbose_name_plural': 'Scrapy jobs'},
        ),
        migrations.AddField(
            model_name='scrapyjobmodel',
            name='finished_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapyjobmodel',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
