# Generated by Django 5.0.1 on 2024-02-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_api', '0006_alter_scrapyjobmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapyjobmodel',
            options={'ordering': ['-supposed_to_run_at'], 'verbose_name': 'Scrapy job', 'verbose_name_plural': 'Scrapy jobs'},
        ),
        migrations.AddField(
            model_name='scrapyjobmodel',
            name='failed_reason',
            field=models.TextField(null=True),
        ),
    ]
