# Generated by Django 5.0.1 on 2024-03-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_api', '0006_alter_scrapyjobmodel_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapyjobmodel',
            name='domain',
            field=models.URLField(null=True, unique=True),
        ),
    ]
