# Generated by Django 5.0.2 on 2024-02-17 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingTypeModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200, unique=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Listing type',
                'verbose_name_plural': 'Listing types',
                'db_table': 'listing_types',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PropertyStatusModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200, unique=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Property status',
                'verbose_name_plural': 'Property statuses',
                'db_table': 'property_statuses',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PropertyTypeModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200, unique=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Property type',
                'verbose_name_plural': 'Property types',
                'db_table': 'property_types',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PropertyModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lot_size', models.FloatField(null=True, verbose_name='Lot Size')),
                ('floor_size', models.FloatField(null=True, verbose_name='Floor Size')),
                ('building_size', models.FloatField(null=True, verbose_name='Building Size')),
                ('num_bedrooms', models.IntegerField(default=0, verbose_name='Number of Bedrooms')),
                ('num_bathrooms', models.IntegerField(default=0, verbose_name='Number of Bathrooms')),
                ('num_carspaces', models.IntegerField(default=0, verbose_name='Number of Car Spaces')),
                ('address_line1', models.CharField(max_length=255, null=True, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(max_length=255, null=True, verbose_name='Address Line 2')),
                ('region', models.CharField(db_index=True, max_length=200, null=True, verbose_name='Region')),
                ('central_business_district', models.BooleanField(default=False, verbose_name='Central Business District')),
                ('longitude', models.FloatField(null=True, verbose_name='Longitude')),
                ('latitude', models.FloatField(null=True, verbose_name='Latitude')),
                ('year_built', models.IntegerField(null=True, verbose_name='Year Built')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city', to='domain.citymodel', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'db_table': 'properties',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PropertyListingModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('listing_title', models.CharField(max_length=255, unique=True, verbose_name='Listing Title')),
                ('listing_url', models.URLField(unique=True, verbose_name='Listing URL')),
                ('price', models.FloatField(null=True, verbose_name='Price')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('listing_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_type', to='properties.listingtypemodel', verbose_name='Listing Type')),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estate', to='properties.propertymodel', verbose_name='Estate')),
                ('property_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_status', to='properties.propertystatusmodel', verbose_name='Property Status')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_type', to='properties.propertytypemodel', verbose_name='Property Type')),
            ],
            options={
                'verbose_name': 'Property listing',
                'verbose_name_plural': 'Property listings',
                'db_table': 'property_listings',
                'ordering': ['-id'],
            },
        ),
    ]
