# Generated by Django 5.0.1 on 2024-02-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_propertylistingmodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymodel',
            name='building_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Building Name'),
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='subdivision_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Building Name'),
        ),
    ]
