# Generated by Django 5.0.1 on 2024-02-27 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_propertymodel_building_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylistingmodel',
            name='estate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estate', to='properties.propertymodel', verbose_name='Estate'),
        ),
    ]
