# Generated by Django 5.0.1 on 2024-02-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_propertylistingmodel_estate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylistingmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Price'),
        ),
    ]
