# Generated by Django 5.0.1 on 2024-02-28 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_propertylistingmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylistingmodel',
            name='property_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_status', to='properties.propertystatusmodel', verbose_name='Property Status'),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='subdivision_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Subdivision Name'),
        ),
    ]
