# Generated by Django 5.0.1 on 2024-02-28 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
        ('properties', '0007_pricehistorymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymodel',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='building_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Building Name'),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='building_size',
            field=models.FloatField(blank=True, null=True, verbose_name='Building Size'),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city', to='domain.citymodel', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='floor_size',
            field=models.FloatField(blank=True, null=True, verbose_name='Floor Size'),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='lot_size',
            field=models.FloatField(blank=True, null=True, verbose_name='Lot Size'),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='subdivision_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Subdivision Name'),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='year_built',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year Built'),
        ),
    ]
