# Generated by Django 5.0.1 on 2024-02-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_propertymodel_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylistingmodel',
            name='images',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Images'),
        ),
    ]
