# Generated by Django 5.0.1 on 2024-02-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_propertylistingmodel_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertylistingmodel',
            name='images',
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='amenities',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Amenities'),
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='images',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Images'),
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='other_details',
            field=models.JSONField(blank=True, null=True, verbose_name='Other Details'),
        ),
    ]
