# Generated by Django 5.0.1 on 2024-03-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_remove_propertylistingmodel_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertymodel',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='propertymodel',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='propertymodel',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='propertymodel',
            name='central_business_district',
        ),
        migrations.RemoveField(
            model_name='propertymodel',
            name='images',
        ),
        migrations.RemoveField(
            model_name='propertymodel',
            name='other_details',
        ),
        migrations.RemoveField(
            model_name='propertymodel',
            name='region',
        ),
        migrations.RemoveField(
            model_name='propertymodel',
            name='year_built',
        ),
        migrations.AddField(
            model_name='propertylistingmodel',
            name='price_formatted',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Price Formatted'),
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Image URL'),
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='indoor_features',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Amenities'),
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='metadata',
            field=models.JSONField(blank=True, null=True, verbose_name='Other Details'),
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='other_features',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Amenities'),
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='outdoor_features',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Amenities'),
        ),
    ]
