# Generated by Django 5.0.1 on 2024-03-02 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_remove_propertymodel_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylistingmodel',
            name='estate',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estate_listing', to='properties.propertymodel', verbose_name='Estate'),
        ),
    ]
