# Generated by Django 5.0.1 on 2024-03-02 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_alter_propertylistingmodel_estate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylistingmodel',
            name='listing_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_type', to='properties.listingtypemodel', verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='propertylistingmodel',
            name='property_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_type', to='properties.propertytypemodel', verbose_name='Property Type'),
        ),
    ]
