# Generated by Django 5.0.1 on 2024-03-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_propertylistingmodel_is_delisted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymodel',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
    ]
