# Generated by Django 5.0.1 on 2024-03-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_alter_propertymodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
