# Generated by Django 5.0.1 on 2024-03-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_alter_propertymodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylistingmodel',
            name='listing_title',
            field=models.TextField(unique=True, verbose_name='Listing Title'),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='building_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Building Name'),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='subdivision_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subdivision Name'),
        ),
    ]
