# Generated by Django 5.0.1 on 2024-03-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_alter_propertylistingmodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylistingmodel',
            name='vector_uuids',
            field=models.TextField(blank=True, null=True, verbose_name='Vector UUIDS'),
        ),
    ]
