# Generated by Django 5.0.1 on 2024-03-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_propertylistingmodel_vector_uuids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylistingmodel',
            name='vector_uuids',
            field=models.JSONField(blank=True, default=list, verbose_name='Vector UUIDs'),
        ),
    ]
