# Generated by Django 5.0.1 on 2024-03-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_propertylistingmodel_is_in_vector_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylistingmodel',
            name='price_formatted',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Price Formatted'),
        ),
    ]
