# Generated by Django 5.0.1 on 2024-03-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0025_listingtypemodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingtypemodel',
            name='slug',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
