# Generated by Django 5.0.1 on 2024-03-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0028_propertytypemodel_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytypemodel',
            name='slug',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
