# Generated by Django 5.0.1 on 2024-03-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0029_alter_propertytypemodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylistingmodel',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='listingtypemodel',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='propertytypemodel',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
