# Generated by Django 5.0.1 on 2024-03-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0030_propertylistingmodel_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylistingmodel',
            name='slug',
            field=models.SlugField(max_length=1000, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
