# Generated by Django 5.0.1 on 2024-03-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0031_alter_propertylistingmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymodel',
            name='ai_generated_description',
            field=models.BooleanField(default=False, verbose_name='AI Generated Description'),
        ),
    ]
