# Generated by Django 5.0.1 on 2024-03-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citymodel',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Name'),
        ),
        migrations.AddIndex(
            model_name='citymodel',
            index=models.Index(fields=['name'], name='city_model_name_idx'),
        ),
    ]
