# Generated by Django 5.0.1 on 2024-03-03 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_alter_citymodel_name_citymodel_city_model_name_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='citymodel',
            new_name='name_idx',
            old_name='city_model_name_idx',
        ),
    ]
