# Generated by Django 5.0.1 on 2024-03-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_rename_city_model_name_idx_name_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citymodel',
            options={'ordering': ['name'], 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
    ]
