# Generated by Django 5.0.1 on 2024-03-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_alter_citymodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='citymodel',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
