# Generated by Django 5.0.1 on 2024-01-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('thread_id', models.CharField(max_length=100, unique=True)),
                ('thread_title', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Thread',
                'verbose_name_plural': 'Threads',
                'db_table': 'threads',
                'ordering': ['id'],
            },
        ),
    ]
