name: kmc_vitro_docker_server_deployment

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run-build-docker-compose:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Grant execute permissions to validate_env_vars.sh
        run: chmod +x ./validate_env_vars.sh
      - name: Execute environment variable validation
        run: ./validate_env_vars.sh
      - name: Check if containers are running
        id: check_containers
        run: |
          RUNNING_CONTAINERS=$(docker compose -f docker-compose-production.yml ps -q)
          if [ -z "$RUNNING_CONTAINERS" ]; then
            echo "Containers are not running, starting them..."
            echo "containers_up=false" >> $GITHUB_OUTPUT
          else
            echo "All containers are already running."
            echo "containers_up=true" >> $GITHUB_OUTPUT
          fi
      - name: Start containers if not running
        if: steps.check_containers.outputs.containers_up == 'false'
        run: docker compose -f docker-compose-production.yml up -d
      - name: Run and build docker-compose file
        run: docker compose -f docker-compose-production.yml build



