name: kmc_vitro_docker_server_deployment

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run-build-docker-compose:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run and build docker-compose file
        run: docker compose -f docker-compose-production.yml build
      - name: Check if API container is running and restart if necessary
        id: check_and_restart_api_container
        run: |
          if ! docker compose -f docker-compose-production.yml ps | grep -q mytreehouse_api_production; then
            echo "mytreehouse_api_production is not running. Attempting to restart..."
            docker compose -f docker-compose-production.yml restart django
          else
            echo "mytreehouse_api_production is already running. No action needed."
          fi
          
          echo "Stopping mytreehouse_worker_production if it is running..."
          docker compose -f docker-compose-production.yml stop worker


