name: kmc_vitro_docker_server_deployment

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run-build-docker-compose:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run and build docker-compose file
        run: docker compose -f docker-compose-production.yml build
      - name: Check if specific containers are running and restart if necessary
        id: check_and_restart_containers
        run: |
          REQUIRED_CONTAINERS="mytreehouse_redis_production mytreehouse_celery_production mytreehouse_worker_production mytreehouse_api_production"
          for CONTAINER in $REQUIRED_CONTAINERS; do
            CONTAINER_NAME=$(echo $CONTAINER | sed 's/mytreehouse_//;s/_production//')
            if ! docker compose -f docker-compose-production.yml ps | grep -q $CONTAINER; then
              echo "$CONTAINER is not running. Attempting to restart..."
              docker compose -f docker-compose-production.yml restart $CONTAINER_NAME
            else
              echo "$CONTAINER is already running. No action needed."
            fi
          done



