name: Trigger auto deployment for mytreehouse

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/mytreehouse-AutoDeployTrigger-b4c5ca63-585c-4f12-8105-51954a153c2d.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MYTREEHOUSE_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: mytreehouse.azurecr.io
          registryUsername: ${{ secrets.MYTREEHOUSE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MYTREEHOUSE_REGISTRY_PASSWORD }}
          containerAppName: mytreehouse
          resourceGroup: CONTAINER_APPS
          imageToBuild: mytreehouse.azurecr.io/mytreehouse:${{ github.sha }}
          
            

     

